import { cache } from "react"
import { queryRows } from "../connection"

/**
 * Code-to-name lookups for the numeric codes the entity tables carry.
 *
 * None of these names are ours. `armour_classes`, `charge_types` and
 * `unit_traits` are generated by the sync script from aoe2techtree's own
 * `js/techtree.js` and `js/main.js`, which is the only place upstream names
 * them, so they refresh with the rest of the export.
 */

export interface ArmourClass {
  id: number
  name: string
  /** Upstream's own qualifier, e.g. "except Camels" on Mounted Units. */
  note: string | null
}

export interface ChargeType {
  id: number
  name: string
}

export interface UnitTrait {
  bit: number
  name: string
  note: string | null
  /** Set when the trait names another entity via the unit's `trait_piece`. */
  piece_kind: "building" | "unit_or_building" | null
}

export const getArmourClasses = cache(async (): Promise<Map<number, ArmourClass>> => {
  const rows = await queryRows<ArmourClass>("SELECT id, name, note FROM armour_classes")
  return new Map(rows.map((row) => [row.id, row]))
})

export const getChargeTypes = cache(async (): Promise<Map<number, ChargeType>> => {
  const rows = await queryRows<ChargeType>("SELECT id, name FROM charge_types")
  return new Map(rows.map((row) => [row.id, row]))
})

export const getUnitTraits = cache(async (): Promise<UnitTrait[]> => {
  return queryRows<UnitTrait>("SELECT bit, name, note, piece_kind FROM unit_traits ORDER BY bit")
})
